FROM golang:1.21-alpine as builder

WORKDIR /app
COPY . .

RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o grpc-user-service .

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/grpc-user-service .

EXPOSE 50051
CMD ["./grpc-user-service"]
